# Generated by Django 4.1a1 on 2022-05-23 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('quantite', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='paire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('marque', models.CharField(max_length=100)),
                ('annee', models.DateField(blank=True, null=True)),
                ('couleur', models.CharField(max_length=100)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('ville', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stockpaire.ville')),
            ],
        ),
    ]
